<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RaceResultSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $race_result_data = [
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '1',
                'race_location_id' => '7',
                'exacta_first' => '2',
                'exacta_second' => '3',
                'exacta_refund_price' => '2060',
                'exacta_rank' => '6',
                'trifecta_first' => '2',
                'trifecta_second' => '3',
                'trifecta_third' => '5',
                'trifecta_refund_price' => '12590',
                'trifecta_rank' => '49',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '2',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '2',
                'exacta_refund_price' => '380',
                'exacta_rank' => '1',
                'trifecta_first' => '1',
                'trifecta_second' => '2',
                'trifecta_third' => '3',
                'trifecta_refund_price' => '1200',
                'trifecta_rank' => '2',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '3',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '4',
                'exacta_refund_price' => '820',
                'exacta_rank' => '4',
                'trifecta_first' => '1',
                'trifecta_second' => '4',
                'trifecta_third' => '6',
                'trifecta_refund_price' => '7530',
                'trifecta_rank' => '23',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '4',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '2',
                'exacta_refund_price' => '820',
                'exacta_rank' => '4',
                'trifecta_first' => '1',
                'trifecta_second' => '2',
                'trifecta_third' => '4',
                'trifecta_refund_price' => '1590',
                'trifecta_rank' => '4',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '5',
                'race_location_id' => '7',
                'exacta_first' => '3',
                'exacta_second' => '4',
                'exacta_refund_price' => '3580',
                'exacta_rank' => '1',
                'trifecta_first' => '3',
                'trifecta_second' => '4',
                'trifecta_third' => '1',
                'trifecta_refund_price' => '6720',
                'trifecta_rank' => '21',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '6',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '2',
                'exacta_refund_price' => '320',
                'exacta_rank' => '1',
                'trifecta_first' => '1',
                'trifecta_second' => '2',
                'trifecta_third' => '3',
                'trifecta_refund_price' => '950',
                'trifecta_rank' => '2',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '7',
                'race_location_id' => '7',
                'exacta_first' => '6',
                'exacta_second' => '2',
                'exacta_refund_price' => '1360',
                'exacta_rank' => '5',
                'trifecta_first' => '6',
                'trifecta_second' => '2',
                'trifecta_third' => '5',
                'trifecta_refund_price' => '8030',
                'trifecta_rank' => '34',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '8',
                'race_location_id' => '7',
                'exacta_first' => '6',
                'exacta_second' => '1',
                'exacta_refund_price' => '9900',
                'exacta_rank' => '18',
                'trifecta_first' => '6',
                'trifecta_second' => '1',
                'trifecta_third' => '2',
                'trifecta_refund_price' => '40510',
                'trifecta_rank' => '70',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '9',
                'race_location_id' => '7',
                'exacta_first' => '3',
                'exacta_second' => '4',
                'exacta_refund_price' => '6750',
                'exacta_rank' => '17',
                'trifecta_first' => '3',
                'trifecta_second' => '4',
                'trifecta_third' => '5',
                'trifecta_refund_price' => '17010',
                'trifecta_rank' => '47',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '10',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '4',
                'exacta_refund_price' => '550',
                'exacta_rank' => '3',
                'trifecta_first' => '1',
                'trifecta_second' => '4',
                'trifecta_third' => '5',
                'trifecta_refund_price' => '2830',
                'trifecta_rank' => '13',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '11',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '2',
                'exacta_refund_price' => '340',
                'exacta_rank' => '1',
                'trifecta_first' => '1',
                'trifecta_second' => '2',
                'trifecta_third' => '4',
                'trifecta_refund_price' => '1110',
                'trifecta_rank' => '1',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-01',
                'race_number' => '12',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '5',
                'exacta_refund_price' => '2040',
                'exacta_rank' => '6',
                'trifecta_first' => '1',
                'trifecta_second' => '5',
                'trifecta_third' => '2',
                'trifecta_refund_price' => '8630',
                'trifecta_rank' => '26',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '1',
                'race_location_id' => '7',
                'exacta_first' => '4',
                'exacta_second' => '1',
                'exacta_refund_price' => '2270',
                'exacta_rank' => '7',
                'trifecta_first' => '4',
                'trifecta_second' => '1',
                'trifecta_third' => '5',
                'trifecta_refund_price' => '8180',
                'trifecta_rank' => '29',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '2',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '2',
                'exacta_refund_price' => '740',
                'exacta_rank' => '7',
                'trifecta_first' => '2',
                'trifecta_second' => '1',
                'trifecta_third' => '4',
                'trifecta_refund_price' => '1570',
                'trifecta_rank' => '5',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '3',
                'race_location_id' => '7',
                'exacta_first' => '2',
                'exacta_second' => '1',
                'exacta_refund_price' => '740',
                'exacta_rank' => '3',
                'trifecta_first' => '2',
                'trifecta_second' => '1',
                'trifecta_third' => '4',
                'trifecta_refund_price' => '1570',
                'trifecta_rank' => '5',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '4',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '4',
                'exacta_refund_price' => '540',
                'exacta_rank' => '7',
                'trifecta_first' => '1',
                'trifecta_second' => '4',
                'trifecta_third' => '5',
                'trifecta_refund_price' => '1490',
                'trifecta_rank' => '2',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '5',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '6',
                'exacta_refund_price' => '830',
                'exacta_rank' => '3',
                'trifecta_first' => '1',
                'trifecta_second' => '6',
                'trifecta_third' => '2',
                'trifecta_refund_price' => '2860',
                'trifecta_rank' => '3',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '6',
                'race_location_id' => '7',
                'exacta_first' => '6',
                'exacta_second' => '5',
                'exacta_refund_price' => '2070',
                'exacta_rank' => '10',
                'trifecta_first' => '6',
                'trifecta_second' => '5',
                'trifecta_third' => '4',
                'trifecta_refund_price' => '19280',
                'trifecta_rank' => '49',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '7',
                'race_location_id' => '7',
                'exacta_first' => '2',
                'exacta_second' => '5',
                'exacta_refund_price' => '8600',
                'exacta_rank' => '7',
                'trifecta_first' => '2',
                'trifecta_second' => '5',
                'trifecta_third' => '1',
                'trifecta_refund_price' => '19280',
                'trifecta_rank' => '29',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '8',
                'race_location_id' => '7',
                'exacta_first' => '4',
                'exacta_second' => '6',
                'exacta_refund_price' => '1160',
                'exacta_rank' => '8',
                'trifecta_first' => '4',
                'trifecta_second' => '6',
                'trifecta_third' => '1',
                'trifecta_refund_price' => '7750',
                'trifecta_rank' => '15',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '9',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '4',
                'exacta_refund_price' => '590',
                'exacta_rank' => '3',
                'trifecta_first' => '1',
                'trifecta_second' => '4',
                'trifecta_third' => '6',
                'trifecta_refund_price' => '4140',
                'trifecta_rank' => '15',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '10',
                'race_location_id' => '7',
                'exacta_first' => '5',
                'exacta_second' => '2',
                'exacta_refund_price' => '5670',
                'exacta_rank' => '16',
                'trifecta_first' => '5',
                'trifecta_second' => '2',
                'trifecta_third' => '3',
                'trifecta_refund_price' => '15260',
                'trifecta_rank' => '46',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '11',
                'race_location_id' => '7',
                'exacta_first' => '1',
                'exacta_second' => '2',
                'exacta_refund_price' => '1230',
                'exacta_rank' => '1',
                'trifecta_first' => '1',
                'trifecta_second' => '2',
                'trifecta_third' => '6',
                'trifecta_refund_price' => '1230',
                'trifecta_rank' => '3',
            ],
            [
                'race_name' => 'オールジャパン竹島特別開設６８周年記念競走',
                'race_date' => '2023-06-02',
                'race_number' => '12',
                'race_location_id' => '7',
                'exacta_first' => '3',
                'exacta_second' => '6',
                'exacta_refund_price' => '3010',
                'exacta_rank' => '11',
                'trifecta_first' => '3',
                'trifecta_second' => '6',
                'trifecta_third' => '1',
                'trifecta_refund_price' => '11170',
                'trifecta_rank' => '40',
            ],
        ];

        DB::table('race_results')->insert($race_result_data);
    }
}
